# Generated by Django 4.1.7 on 2023-03-29 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "party",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Human"),
                            (2, "2 Human"),
                            (3, "3 Human"),
                            (4, "4 Human"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "table",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1  Table"),
                            (2, "2  Table"),
                            (3, "3  Table"),
                            (4, "4  Table"),
                            (5, "5  Table"),
                            (6, "6  Table"),
                            (7, "7  Table"),
                            (8, "8  Table"),
                            (9, "9  Table"),
                            (10, "10  Table"),
                        ],
                        default=1,
                    ),
                ),
                ("phone", models.IntegerField()),
                (
                    "spending_time",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1 hour"), (2, "2 hour")], default=1
                    ),
                ),
                ("present_date_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                ("price", models.IntegerField()),
                ("thumb", models.ImageField(default="default.png", upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
